name: Atualizar e Triar CSVs TEDE2

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 1 1,7 *'
    - cron: '0 4 2 1,7 *'

jobs:
  atualizar-csvs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run update script
        run: python update_tede_csv.py
      - name: Upload CSVs como artefatos
        uses: actions/upload-artifact@v4
        with:
          name: csvs-tede2
          path: ./csvs/*.csv

  triagem-inovacao:
    runs-on: ubuntu-latest
    needs: atualizar-csvs
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pandas gspread google-auth
      - name: Download CSVs artifact
        uses: actions/download-artifact@v4
        with:
          name: csvs-tede2
      - name: Criar pasta csvs
        run: mkdir -p csvs
      - name: Copiar arquivos CSVs para pasta csvs
        run: mv *.csv csvs/
      - name: Triagem inovação e exportação para Sheets
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: python triagem_inovacao.py
